//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antares.model {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("Proveedores", Schema="dbo")]
    public partial class Proveedores : ActiveRecordBase<Proveedores> {
        
        private int _id;
        
        private string _descripcion;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
    }
    
    [ActiveRecord("Factura_Estados", Schema="dbo")]
    public partial class FacturaEstados : ActiveRecordBase<FacturaEstados> {
        
        private int _id;
        
        private string _descripcion;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
    }
    
    [ActiveRecord("Pagos_Efectuados", Schema="dbo")]
    public partial class PagosEfectuados : ActiveRecordBase<PagosEfectuados> {
        
        private int _id;
        
        private System.DateTime _fechaPago;
        
        private int _idProveedor;
        
        private int _facturaProveedor;
        
        private int _nroPago;
        
        private int _idBanco;
        
        private int _idFormaPago;
        
        private decimal _importePago;
        
        private string _reciboPagoCliente;
        
        private System.DateTime _fechaActualizacion;
        
        private string _comentarios;
        
        private string _estadoPago;
        
        private bool _ingresadoCaja;
        
        private bool _conciliadoBanco;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Fecha_Pago", ColumnType="DateTime")]
        public virtual System.DateTime FechaPago {
            get {
                return this._fechaPago;
            }
            set {
                this._fechaPago = value;
            }
        }
        
        [Property("Id_Proveedor", ColumnType="Int32")]
        public virtual int IdProveedor {
            get {
                return this._idProveedor;
            }
            set {
                this._idProveedor = value;
            }
        }
        
        [Property("Factura_Proveedor", ColumnType="Int32")]
        public virtual int FacturaProveedor {
            get {
                return this._facturaProveedor;
            }
            set {
                this._facturaProveedor = value;
            }
        }
        
        [Property("Nro_Pago", ColumnType="Int32")]
        public virtual int NroPago {
            get {
                return this._nroPago;
            }
            set {
                this._nroPago = value;
            }
        }
        
        [Property("Id_Banco", ColumnType="Int32")]
        public virtual int IdBanco {
            get {
                return this._idBanco;
            }
            set {
                this._idBanco = value;
            }
        }
        
        [Property("Id_Forma_Pago", ColumnType="Int32")]
        public virtual int IdFormaPago {
            get {
                return this._idFormaPago;
            }
            set {
                this._idFormaPago = value;
            }
        }
        
        [Property("Importe_Pago", ColumnType="Decimal")]
        public virtual decimal ImportePago {
            get {
                return this._importePago;
            }
            set {
                this._importePago = value;
            }
        }
        
        [Property("Recibo_Pago_Cliente", ColumnType="String")]
        public virtual string ReciboPagoCliente {
            get {
                return this._reciboPagoCliente;
            }
            set {
                this._reciboPagoCliente = value;
            }
        }
        
        [Property("Fecha_Actualizacion", ColumnType="Timestamp")]
        public virtual System.DateTime FechaActualizacion {
            get {
                return this._fechaActualizacion;
            }
            set {
                this._fechaActualizacion = value;
            }
        }
        
        [Property("Comentarios", ColumnType="String")]
        public virtual string Comentarios {
            get {
                return this._comentarios;
            }
            set {
                this._comentarios = value;
            }
        }
        
        [Property("Estado_Pago", ColumnType="String")]
        public virtual string EstadoPago {
            get {
                return this._estadoPago;
            }
            set {
                this._estadoPago = value;
            }
        }
        
        [Property("Ingresado_Caja", ColumnType="Boolean")]
        public virtual bool IngresadoCaja {
            get {
                return this._ingresadoCaja;
            }
            set {
                this._ingresadoCaja = value;
            }
        }
        
        [Property("Conciliado_Banco", ColumnType="Boolean")]
        public virtual bool ConciliadoBanco {
            get {
                return this._conciliadoBanco;
            }
            set {
                this._conciliadoBanco = value;
            }
        }
    }
    
    [ActiveRecord("Facturas", Schema="dbo")]
    public partial class Facturas : ActiveRecordBase<Facturas> {
        
        private int _id;
        
        private int _idFacturaEstados;
        
        private int _idProveedor;
        
        private System.DateTime _fecha;
        
        private string _nFactura;
        
        private string _descripcion;
        
        private System.DateTime _fechaRecepcionFactura;
        
        private string _plazoPago;
        
        private decimal _importeGravado;
        
        private decimal _importeNoGravado;
        
        private decimal _porcentajeIva;
        
        private decimal _importeTotal;
        
        private decimal _montoRetencion;
        
        private System.DateTime _fechaActualizacion;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Id_Factura_Estados", ColumnType="Int32")]
        public virtual int IdFacturaEstados {
            get {
                return this._idFacturaEstados;
            }
            set {
                this._idFacturaEstados = value;
            }
        }
        
        [Property("Id_Proveedor", ColumnType="Int32")]
        public virtual int IdProveedor {
            get {
                return this._idProveedor;
            }
            set {
                this._idProveedor = value;
            }
        }
        
        [Property("Fecha", ColumnType="DateTime")]
        public virtual System.DateTime Fecha {
            get {
                return this._fecha;
            }
            set {
                this._fecha = value;
            }
        }
        
        [Property("n_factura", ColumnType="String")]
        public virtual string NFactura {
            get {
                return this._nFactura;
            }
            set {
                this._nFactura = value;
            }
        }
        
        [Property("descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
        
        [Property("Fecha_Recepcion_Factura", ColumnType="DateTime")]
        public virtual System.DateTime FechaRecepcionFactura {
            get {
                return this._fechaRecepcionFactura;
            }
            set {
                this._fechaRecepcionFactura = value;
            }
        }
        
        [Property("Plazo_Pago", ColumnType="String")]
        public virtual string PlazoPago {
            get {
                return this._plazoPago;
            }
            set {
                this._plazoPago = value;
            }
        }
        
        [Property("Importe_Gravado", ColumnType="Decimal")]
        public virtual decimal ImporteGravado {
            get {
                return this._importeGravado;
            }
            set {
                this._importeGravado = value;
            }
        }
        
        [Property("Importe_no_Gravado", ColumnType="Decimal")]
        public virtual decimal ImporteNoGravado {
            get {
                return this._importeNoGravado;
            }
            set {
                this._importeNoGravado = value;
            }
        }
        
        [Property("Porcentaje_Iva", ColumnType="Decimal")]
        public virtual decimal PorcentajeIva {
            get {
                return this._porcentajeIva;
            }
            set {
                this._porcentajeIva = value;
            }
        }
        
        [Property("Importe_Total", ColumnType="Decimal")]
        public virtual decimal ImporteTotal {
            get {
                return this._importeTotal;
            }
            set {
                this._importeTotal = value;
            }
        }
        
        [Property("Monto_Retencion", ColumnType="Decimal")]
        public virtual decimal MontoRetencion {
            get {
                return this._montoRetencion;
            }
            set {
                this._montoRetencion = value;
            }
        }
        
        [Property("Fecha_Actualizacion", ColumnType="DateTime", Insert=false, Update=false)]
        public virtual System.DateTime FechaActualizacion {
            get {
                return this._fechaActualizacion;
            }
            set {
                this._fechaActualizacion = value;
            }
        }
    }
}
