//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antares.model {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("Tipo_Solicitud", Schema="dbo")]
    public partial class TipoSolicitud : ActiveRecordBase<TipoSolicitud> {
        
        private int _idTiposolicitud;
        
        private string _descripcion;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id_TipoSolicitud", ColumnType="Int32")]
        public virtual int IdTiposolicitud {
            get {
                return this._idTiposolicitud;
            }
            set {
                this._idTiposolicitud = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
    }
    
    [ActiveRecord("Tareas", Schema="dbo")]
    public partial class Tareas : ActiveRecordBase<Tareas> {
        
        private int _id;
        
        private string _tarea;
        
        [PrimaryKey(PrimaryKeyType.Native, "id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Tarea", ColumnType="String")]
        public virtual string Tarea {
            get {
                return this._tarea;
            }
            set {
                this._tarea = value;
            }
        }
    }
    
    [ActiveRecord("Empresas", Schema="dbo")]
    public partial class Empresas : ActiveRecordBase<Empresas> {
        
        private int _idEmpresa;
        
        private string _nombre;
        
        private string _telefono;
        
        private string _localidad;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id_Empresa", ColumnType="Int32")]
        public virtual int IdEmpresa {
            get {
                return this._idEmpresa;
            }
            set {
                this._idEmpresa = value;
            }
        }
        
        [Property("Nombre", ColumnType="String")]
        public virtual string Nombre {
            get {
                return this._nombre;
            }
            set {
                this._nombre = value;
            }
        }
        
        [Property("Telefono", ColumnType="String")]
        public virtual string Telefono {
            get {
                return this._telefono;
            }
            set {
                this._telefono = value;
            }
        }
        
        [Property("Localidad", ColumnType="String")]
        public virtual string Localidad {
            get {
                return this._localidad;
            }
            set {
                this._localidad = value;
            }
        }
    }
    
    [ActiveRecord("Servicios", Schema="dbo")]
    public partial class Servicios : ActiveRecordBase<Servicios> {
        
        private int _id;
        
        private string _codigo;
        
        private string _descripcion;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Codigo", ColumnType="AnsiChar")]
        public virtual string Codigo {
            get {
                return this._codigo;
            }
            set {
                this._codigo = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
    }
    
    [ActiveRecord("Plazo_Realizacion", Schema="dbo")]
    public partial class PlazoRealizacion : ActiveRecordBase<PlazoRealizacion> {
        
        private int _id;
        
        private string _descripcion;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Servicios_Afectados", Schema="dbo")]
    public partial class SolicitudServiciosAfectados : ActiveRecordBase<SolicitudServiciosAfectados> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private int _idServicioAfectado;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("IdSolicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("IdServicioAfectado", ColumnType="Int32")]
        public virtual int IdServicioAfectado {
            get {
                return this._idServicioAfectado;
            }
            set {
                this._idServicioAfectado = value;
            }
        }
    }
    
    [ActiveRecord("TipoTarea", Schema="dbo")]
    public partial class TipoTarea : ActiveRecordBase<TipoTarea> {
        
        private int _id;
        
        private string _descripcion;
        
        private string _descripcionLarga;
        
        [PrimaryKey(PrimaryKeyType.Native, "id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
        
        [Property("Descripcion_Larga", ColumnType="String")]
        public virtual string DescripcionLarga {
            get {
                return this._descripcionLarga;
            }
            set {
                this._descripcionLarga = value;
            }
        }
    }
    
    [ActiveRecord("Tipo_Licencia", Schema="dbo")]
    public partial class TipoLicencia : ActiveRecordBase<TipoLicencia> {
        
        private int _id;
        
        private string _descripcion;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
    }
    
    [ActiveRecord("Usuarios_Empleados", Schema="dbo")]
    public partial class UsuariosEmpleados : ActiveRecordBase<UsuariosEmpleados> {
        
        private int _idUsuarioEmpleado;
        
        private int _idEmpleados;
        
        private int _idUsuarios;
        
        private System.DateTime _fecha;
        
        [PrimaryKey(PrimaryKeyType.Native, "id_Usuario_Empleado", ColumnType="Int32")]
        public virtual int IdUsuarioEmpleado {
            get {
                return this._idUsuarioEmpleado;
            }
            set {
                this._idUsuarioEmpleado = value;
            }
        }
        
        [Property("Id_Empleados", ColumnType="Int32", NotNull=true)]
        public virtual int IdEmpleados {
            get {
                return this._idEmpleados;
            }
            set {
                this._idEmpleados = value;
            }
        }
        
        [Property("Id_Usuarios", ColumnType="Int32", NotNull=true)]
        public virtual int IdUsuarios {
            get {
                return this._idUsuarios;
            }
            set {
                this._idUsuarios = value;
            }
        }
        
        [Property("Fecha", ColumnType="Timestamp")]
        public virtual System.DateTime Fecha {
            get {
                return this._fecha;
            }
            set {
                this._fecha = value;
            }
        }
    }
    
    [ActiveRecord("TipoSolicitud_X_Perfil", Schema="dbo")]
    public partial class TiposolicitudXPerfil : ActiveRecordBase<TiposolicitudXPerfil> {
        
        private int _id;
        
        private int _idPerfil;
        
        private int _idTiposolicitud;
        
        [PrimaryKey(PrimaryKeyType.Native, "id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("idPerfil", ColumnType="Int32")]
        public virtual int IdPerfil {
            get {
                return this._idPerfil;
            }
            set {
                this._idPerfil = value;
            }
        }
        
        [Property("Id_TipoSolicitud", ColumnType="Int32")]
        public virtual int IdTiposolicitud {
            get {
                return this._idTiposolicitud;
            }
            set {
                this._idTiposolicitud = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Recursos_Empleados", Schema="dbo")]
    public partial class SolicitudRecursosEmpleados : ActiveRecordBase<SolicitudRecursosEmpleados> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private int _idEmpleado;
        
        private bool _responsable;
        
        private decimal _horas;
        
        private string _detalle;
        
        private string _fecha;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Id_Solicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("Id_Empleado", ColumnType="Int32")]
        public virtual int IdEmpleado {
            get {
                return this._idEmpleado;
            }
            set {
                this._idEmpleado = value;
            }
        }
        
        [Property("Responsable", ColumnType="Boolean")]
        public virtual bool Responsable {
            get {
                return this._responsable;
            }
            set {
                this._responsable = value;
            }
        }
        
        [Property("Horas", ColumnType="Decimal")]
        public virtual decimal Horas {
            get {
                return this._horas;
            }
            set {
                this._horas = value;
            }
        }
        
        [Property("Detalle", ColumnType="String")]
        public virtual string Detalle {
            get {
                return this._detalle;
            }
            set {
                this._detalle = value;
            }
        }
        
        [Property("Fecha", ColumnType="String")]
        public virtual string Fecha {
            get {
                return this._fecha;
            }
            set {
                this._fecha = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Rendicion_Personal_Horas", Schema="dbo")]
    public partial class SolicitudRendicionPersonalHoras : ActiveRecordBase<SolicitudRendicionPersonalHoras> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private int _idPersona;
        
        private System.DateTime _fecha;
        
        private decimal _horas;
        
        private string _descripcion;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Id_solicitud", ColumnType="Int32", NotNull=true)]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("Id_persona", ColumnType="Int32", NotNull=true)]
        public virtual int IdPersona {
            get {
                return this._idPersona;
            }
            set {
                this._idPersona = value;
            }
        }
        
        [Property("Fecha", ColumnType="Timestamp")]
        public virtual System.DateTime Fecha {
            get {
                return this._fecha;
            }
            set {
                this._fecha = value;
            }
        }
        
        [Property("Horas", ColumnType="Decimal", NotNull=true)]
        public virtual decimal Horas {
            get {
                return this._horas;
            }
            set {
                this._horas = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Rendicion_Vehiculos_Horas", Schema="dbo")]
    public partial class SolicitudRendicionVehiculosHoras : ActiveRecordBase<SolicitudRendicionVehiculosHoras> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private int _idVehiculo;
        
        private System.DateTime _fecha;
        
        private decimal _horas;
        
        private string _kilometros;
        
        private string _descripcion;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Id_solicitud", ColumnType="Int32", NotNull=true)]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("Id_Vehiculo", ColumnType="Int32", NotNull=true)]
        public virtual int IdVehiculo {
            get {
                return this._idVehiculo;
            }
            set {
                this._idVehiculo = value;
            }
        }
        
        [Property("Fecha", ColumnType="Timestamp")]
        public virtual System.DateTime Fecha {
            get {
                return this._fecha;
            }
            set {
                this._fecha = value;
            }
        }
        
        [Property("Horas", ColumnType="Decimal", NotNull=true)]
        public virtual decimal Horas {
            get {
                return this._horas;
            }
            set {
                this._horas = value;
            }
        }
        
        [Property("Kilometros", ColumnType="String")]
        public virtual string Kilometros {
            get {
                return this._kilometros;
            }
            set {
                this._kilometros = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Tareas", Schema="dbo")]
    public partial class SolicitudTareas : ActiveRecordBase<SolicitudTareas> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private System.DateTime _fechaFin;
        
        private int _idTarea;
        
        private System.DateTime _fechaInicio;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Id_Solicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("FechaFin", ColumnType="Timestamp")]
        public virtual System.DateTime FechaFin {
            get {
                return this._fechaFin;
            }
            set {
                this._fechaFin = value;
            }
        }
        
        [Property("Id_Tarea", ColumnType="Int32")]
        public virtual int IdTarea {
            get {
                return this._idTarea;
            }
            set {
                this._idTarea = value;
            }
        }
        
        [Property("FechaInicio", ColumnType="Timestamp")]
        public virtual System.DateTime FechaInicio {
            get {
                return this._fechaInicio;
            }
            set {
                this._fechaInicio = value;
            }
        }
    }
    
    [ActiveRecord("Calidad_Archivos", Schema="dbo")]
    public partial class CalidadArchivos : ActiveRecordBase<CalidadArchivos> {
        
        private int _id;
        
        private int _idSitio;
        
        private int _idTarea;
        
        private string _nombreArchivo;
        
        private string _rutaArchivo;
        
        private string _año;
        
        private System.DateTime _fechaActualizacion;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Id_Sitio", ColumnType="Int32")]
        public virtual int IdSitio {
            get {
                return this._idSitio;
            }
            set {
                this._idSitio = value;
            }
        }
        
        [Property("Id_Tarea", ColumnType="Int32")]
        public virtual int IdTarea {
            get {
                return this._idTarea;
            }
            set {
                this._idTarea = value;
            }
        }
        
        [Property("Nombre_Archivo", ColumnType="String")]
        public virtual string NombreArchivo {
            get {
                return this._nombreArchivo;
            }
            set {
                this._nombreArchivo = value;
            }
        }
        
        [Property("Ruta_Archivo", ColumnType="String")]
        public virtual string RutaArchivo {
            get {
                return this._rutaArchivo;
            }
            set {
                this._rutaArchivo = value;
            }
        }
        
        [Property("Año", ColumnType="String")]
        public virtual string Año {
            get {
                return this._año;
            }
            set {
                this._año = value;
            }
        }
        
        [Property("FechaActualizacion", ColumnType="DateTime", Insert=false, Update=false)]
        public virtual System.DateTime FechaActualizacion {
            get {
                return this._fechaActualizacion;
            }
            set {
                this._fechaActualizacion = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Archivo_Calidad", Schema="dbo")]
    public partial class SolicitudArchivoCalidad : ActiveRecordBase<SolicitudArchivoCalidad> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private int _idCalidadArchivo;
        
        private System.DateTime _fechaActualizacion;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Id_Solicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("Id_Calidad_Archivo", ColumnType="Int32")]
        public virtual int IdCalidadArchivo {
            get {
                return this._idCalidadArchivo;
            }
            set {
                this._idCalidadArchivo = value;
            }
        }
        
        [Property("FechaActualizacion", ColumnType="DateTime", Insert=false, Update=false)]
        public virtual System.DateTime FechaActualizacion {
            get {
                return this._fechaActualizacion;
            }
            set {
                this._fechaActualizacion = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Preventivo", Schema="dbo")]
    public partial class SolicitudPreventivo : ActiveRecordBase<SolicitudPreventivo> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private int _idSitio;
        
        private System.DateTime _fechaInicio;
        
        private System.DateTime _fechaFin;
        
        private string _presupuesto;
        
        [PrimaryKey(PrimaryKeyType.Native, "id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("IdSolicitud", ColumnType="Int32", NotNull=true)]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("IdSitio", ColumnType="Int32")]
        public virtual int IdSitio {
            get {
                return this._idSitio;
            }
            set {
                this._idSitio = value;
            }
        }
        
        [Property("Fecha_Inicio", ColumnType="DateTime")]
        public virtual System.DateTime FechaInicio {
            get {
                return this._fechaInicio;
            }
            set {
                this._fechaInicio = value;
            }
        }
        
        [Property("Fecha_Fin", ColumnType="DateTime")]
        public virtual System.DateTime FechaFin {
            get {
                return this._fechaFin;
            }
            set {
                this._fechaFin = value;
            }
        }
        
        [Property("Presupuesto", ColumnType="String")]
        public virtual string Presupuesto {
            get {
                return this._presupuesto;
            }
            set {
                this._presupuesto = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Aprobaciones", Schema="dbo")]
    public partial class SolicitudAprobaciones : ActiveRecordBase<SolicitudAprobaciones> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private string _sector;
        
        private bool _aprobado;
        
        private System.DateTime _fechaActualizacion;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Id_Solicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("Sector", ColumnType="String")]
        public virtual string Sector {
            get {
                return this._sector;
            }
            set {
                this._sector = value;
            }
        }
        
        [Property("Aprobado", ColumnType="Boolean")]
        public virtual bool Aprobado {
            get {
                return this._aprobado;
            }
            set {
                this._aprobado = value;
            }
        }
        
        [Property("FechaActualizacion", ColumnType="DateTime", Insert=false, Update=false)]
        public virtual System.DateTime FechaActualizacion {
            get {
                return this._fechaActualizacion;
            }
            set {
                this._fechaActualizacion = value;
            }
        }
    }
    
    [ActiveRecord("OP_Sitios", Schema="dbo")]
    public partial class Sitios : ActiveRecordBase<Sitios> {
        
        private int _idSitio;
        
        private string _codigo;
        
        private string _descripcion;
        
        private string _nombre;
        
        private string _tipo;
        
        private string _operador;
        
        private string _codigoOperador;
        
        private string _direccion;
        
        private string _cP;
        
        private string _lat;
        
        private string _long;
        
        private string _localidad;
        
        private string _provincia;
        
        private string _uoPrimaria;
        
        private string _uoCodigo;
        
        private string _usuariosSitio;
        
        private bool _activo;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id_Sitio", ColumnType="Int32")]
        public virtual int IdSitio {
            get {
                return this._idSitio;
            }
            set {
                this._idSitio = value;
            }
        }
        
        [Property("Codigo", ColumnType="String")]
        public virtual string Codigo {
            get {
                return this._codigo;
            }
            set {
                this._codigo = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
        
        [Property("Nombre", ColumnType="String")]
        public virtual string Nombre {
            get {
                return this._nombre;
            }
            set {
                this._nombre = value;
            }
        }
        
        [Property("Tipo", ColumnType="String")]
        public virtual string Tipo {
            get {
                return this._tipo;
            }
            set {
                this._tipo = value;
            }
        }
        
        [Property("Operador", ColumnType="String")]
        public virtual string Operador {
            get {
                return this._operador;
            }
            set {
                this._operador = value;
            }
        }
        
        [Property("Codigo_Operador", ColumnType="String")]
        public virtual string CodigoOperador {
            get {
                return this._codigoOperador;
            }
            set {
                this._codigoOperador = value;
            }
        }
        
        [Property("Direccion", ColumnType="String")]
        public virtual string Direccion {
            get {
                return this._direccion;
            }
            set {
                this._direccion = value;
            }
        }
        
        [Property("CP", ColumnType="String")]
        public virtual string CP {
            get {
                return this._cP;
            }
            set {
                this._cP = value;
            }
        }
        
        [Property("Lat", ColumnType="String")]
        public virtual string Lat {
            get {
                return this._lat;
            }
            set {
                this._lat = value;
            }
        }
        
        [Property("Long", ColumnType="String")]
        public virtual string Long {
            get {
                return this._long;
            }
            set {
                this._long = value;
            }
        }
        
        [Property("Localidad", ColumnType="String")]
        public virtual string Localidad {
            get {
                return this._localidad;
            }
            set {
                this._localidad = value;
            }
        }
        
        [Property("Provincia", ColumnType="String")]
        public virtual string Provincia {
            get {
                return this._provincia;
            }
            set {
                this._provincia = value;
            }
        }
        
        [Property("UO_Primaria", ColumnType="String")]
        public virtual string UoPrimaria {
            get {
                return this._uoPrimaria;
            }
            set {
                this._uoPrimaria = value;
            }
        }
        
        [Property("UO_Codigo", ColumnType="String")]
        public virtual string UoCodigo {
            get {
                return this._uoCodigo;
            }
            set {
                this._uoCodigo = value;
            }
        }
        
        [Property("Usuarios_Sitio", ColumnType="String")]
        public virtual string UsuariosSitio {
            get {
                return this._usuariosSitio;
            }
            set {
                this._usuariosSitio = value;
            }
        }
        
        [Property("Activo", ColumnType="Boolean")]
        public virtual bool Activo {
            get {
                return this._activo;
            }
            set {
                this._activo = value;
            }
        }
    }
    
    [ActiveRecord("Vehiculos", Schema="dbo")]
    public partial class Vehiculos : ActiveRecordBase<Vehiculos> {
        
        private int _idVehiculos;
        
        private string _nUnidad;
        
        private string _patente;
        
        private int _dV;
        
        private string _marca;
        
        private string _modelo;
        
        private string _año;
        
        private string _motor;
        
        private string _chasis;
        
        private string _base;
        
        private string _responsable;
        
        private string _aseguradora;
        
        private System.DateTime _vencimientoSeguro;
        
        private System.DateTime _vencimientoCedulaVerde;
        
        private string _estado;
        
        private string _prendado;
        
        private string _color;
        
        private int _fechaCompra;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_Vehiculos", ColumnType="Int32")]
        public virtual int IdVehiculos {
            get {
                return this._idVehiculos;
            }
            set {
                this._idVehiculos = value;
            }
        }
        
        [Property("N_Unidad", ColumnType="String")]
        public virtual string NUnidad {
            get {
                return this._nUnidad;
            }
            set {
                this._nUnidad = value;
            }
        }
        
        [Property("Patente", ColumnType="String")]
        public virtual string Patente {
            get {
                return this._patente;
            }
            set {
                this._patente = value;
            }
        }
        
        [Property("DV", ColumnType="Int32")]
        public virtual int DV {
            get {
                return this._dV;
            }
            set {
                this._dV = value;
            }
        }
        
        [Property("Marca", ColumnType="String")]
        public virtual string Marca {
            get {
                return this._marca;
            }
            set {
                this._marca = value;
            }
        }
        
        [Property("Modelo", ColumnType="String")]
        public virtual string Modelo {
            get {
                return this._modelo;
            }
            set {
                this._modelo = value;
            }
        }
        
        [Property("Año", ColumnType="AnsiString")]
        public virtual string Año {
            get {
                return this._año;
            }
            set {
                this._año = value;
            }
        }
        
        [Property("Motor", ColumnType="String")]
        public virtual string Motor {
            get {
                return this._motor;
            }
            set {
                this._motor = value;
            }
        }
        
        [Property("Chasis", ColumnType="String")]
        public virtual string Chasis {
            get {
                return this._chasis;
            }
            set {
                this._chasis = value;
            }
        }
        
        [Property("Base", ColumnType="String")]
        public virtual string Base {
            get {
                return this._base;
            }
            set {
                this._base = value;
            }
        }
        
        [Property("Responsable", ColumnType="String")]
        public virtual string Responsable {
            get {
                return this._responsable;
            }
            set {
                this._responsable = value;
            }
        }
        
        [Property("Aseguradora", ColumnType="String")]
        public virtual string Aseguradora {
            get {
                return this._aseguradora;
            }
            set {
                this._aseguradora = value;
            }
        }
        
        [Property("Vencimiento_Seguro", ColumnType="DateTime", Update=false)]
        public virtual System.DateTime VencimientoSeguro {
            get {
                return this._vencimientoSeguro;
            }
            set {
                this._vencimientoSeguro = value;
            }
        }
        
        [Property("Vencimiento_Cedula_Verde", ColumnType="DateTime", Update=false)]
        public virtual System.DateTime VencimientoCedulaVerde {
            get {
                return this._vencimientoCedulaVerde;
            }
            set {
                this._vencimientoCedulaVerde = value;
            }
        }
        
        [Property("Estado", ColumnType="String")]
        public virtual string Estado {
            get {
                return this._estado;
            }
            set {
                this._estado = value;
            }
        }
        
        [Property("Prendado", ColumnType="String")]
        public virtual string Prendado {
            get {
                return this._prendado;
            }
            set {
                this._prendado = value;
            }
        }
        
        [Property("Color", ColumnType="String")]
        public virtual string Color {
            get {
                return this._color;
            }
            set {
                this._color = value;
            }
        }
        
        [Property("Fecha_Compra", ColumnType="Int32")]
        public virtual int FechaCompra {
            get {
                return this._fechaCompra;
            }
            set {
                this._fechaCompra = value;
            }
        }
    }
    
    [ActiveRecord("Personal", Schema="dbo")]
    public partial class Personal : ActiveRecordBase<Personal> {
        
        private int _idEmpleados;
        
        private string _nLegajo;
        
        private string _apellido;
        
        private string _nombres;
        
        private string _zona;
        
        private string _base;
        
        private string _telCelular;
        
        private string _telParticular;
        
        private string _celPatrticular;
        
        private string _calle;
        
        private string _numero;
        
        private string _pisoDto;
        
        private string _cP;
        
        private string _localidad;
        
        private string _pcia;
        
        private System.DateTime _fechaNacimiento;
        
        private string _nacionalidad;
        
        private string _docTipo;
        
        private string _docNumero;
        
        private string _cUIL;
        
        private string _cAT;
        
        private string _estadoCivil;
        
        private string _numHijos;
        
        private string _habilitadoConducirV;
        
        private string _bancoEnQuePercibeHaberes;
        
        private string _ctaHaberes;
        
        private string _ctaGalicia;
        
        private string _ctaRio;
        
        private string _ctaParibas;
        
        private string _tipoDeContrato;
        
        private string _numContrato;
        
        private System.DateTime _fechaDeIngreso;
        
        private System.DateTime _fechaFinContrato;
        
        private string _activo;
        
        private string _puesto;
        
        private System.DateTime _ultimoExamenPeriodico;
        
        private string _foto;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id_Empleados", ColumnType="Int32")]
        public virtual int IdEmpleados {
            get {
                return this._idEmpleados;
            }
            set {
                this._idEmpleados = value;
            }
        }
        
        [Property("N_Legajo", ColumnType="AnsiString")]
        public virtual string NLegajo {
            get {
                return this._nLegajo;
            }
            set {
                this._nLegajo = value;
            }
        }
        
        [Property("Apellido", ColumnType="String", NotNull=true)]
        public virtual string Apellido {
            get {
                return this._apellido;
            }
            set {
                this._apellido = value;
            }
        }
        
        [Property("Nombres", ColumnType="String", NotNull=true)]
        public virtual string Nombres {
            get {
                return this._nombres;
            }
            set {
                this._nombres = value;
            }
        }
        
        [Property("Zona", ColumnType="String")]
        public virtual string Zona {
            get {
                return this._zona;
            }
            set {
                this._zona = value;
            }
        }
        
        [Property("Base", ColumnType="String")]
        public virtual string Base {
            get {
                return this._base;
            }
            set {
                this._base = value;
            }
        }
        
        [Property("Tel_Celular", ColumnType="String")]
        public virtual string TelCelular {
            get {
                return this._telCelular;
            }
            set {
                this._telCelular = value;
            }
        }
        
        [Property("Tel_Particular", ColumnType="String")]
        public virtual string TelParticular {
            get {
                return this._telParticular;
            }
            set {
                this._telParticular = value;
            }
        }
        
        [Property("Cel_Patrticular", ColumnType="String")]
        public virtual string CelPatrticular {
            get {
                return this._celPatrticular;
            }
            set {
                this._celPatrticular = value;
            }
        }
        
        [Property("Calle", ColumnType="String")]
        public virtual string Calle {
            get {
                return this._calle;
            }
            set {
                this._calle = value;
            }
        }
        
        [Property("Numero", ColumnType="String")]
        public virtual string Numero {
            get {
                return this._numero;
            }
            set {
                this._numero = value;
            }
        }
        
        [Property("Piso_Dto", ColumnType="String")]
        public virtual string PisoDto {
            get {
                return this._pisoDto;
            }
            set {
                this._pisoDto = value;
            }
        }
        
        [Property("CP", ColumnType="String")]
        public virtual string CP {
            get {
                return this._cP;
            }
            set {
                this._cP = value;
            }
        }
        
        [Property("Localidad", ColumnType="String")]
        public virtual string Localidad {
            get {
                return this._localidad;
            }
            set {
                this._localidad = value;
            }
        }
        
        [Property("Pcia", ColumnType="String")]
        public virtual string Pcia {
            get {
                return this._pcia;
            }
            set {
                this._pcia = value;
            }
        }
        
        [Property("Fecha_Nacimiento", ColumnType="DateTime", Insert=false, Update=false)]
        public virtual System.DateTime FechaNacimiento {
            get {
                return this._fechaNacimiento;
            }
            set {
                this._fechaNacimiento = value;
            }
        }
        
        [Property("Nacionalidad", ColumnType="String")]
        public virtual string Nacionalidad {
            get {
                return this._nacionalidad;
            }
            set {
                this._nacionalidad = value;
            }
        }
        
        [Property("Doc_Tipo", ColumnType="String")]
        public virtual string DocTipo {
            get {
                return this._docTipo;
            }
            set {
                this._docTipo = value;
            }
        }
        
        [Property("Doc_Numero", ColumnType="String")]
        public virtual string DocNumero {
            get {
                return this._docNumero;
            }
            set {
                this._docNumero = value;
            }
        }
        
        [Property("CUIL", ColumnType="String")]
        public virtual string CUIL {
            get {
                return this._cUIL;
            }
            set {
                this._cUIL = value;
            }
        }
        
        [Property("CAT", ColumnType="String")]
        public virtual string CAT {
            get {
                return this._cAT;
            }
            set {
                this._cAT = value;
            }
        }
        
        [Property("Estado_Civil", ColumnType="String")]
        public virtual string EstadoCivil {
            get {
                return this._estadoCivil;
            }
            set {
                this._estadoCivil = value;
            }
        }
        
        [Property("Num_Hijos", ColumnType="String")]
        public virtual string NumHijos {
            get {
                return this._numHijos;
            }
            set {
                this._numHijos = value;
            }
        }
        
        [Property("Habilitado_Conducir_V", ColumnType="String", NotNull=true)]
        public virtual string HabilitadoConducirV {
            get {
                return this._habilitadoConducirV;
            }
            set {
                this._habilitadoConducirV = value;
            }
        }
        
        [Property("Banco_en_que_percibe_Haberes", ColumnType="String")]
        public virtual string BancoEnQuePercibeHaberes {
            get {
                return this._bancoEnQuePercibeHaberes;
            }
            set {
                this._bancoEnQuePercibeHaberes = value;
            }
        }
        
        [Property("Cta_Haberes", ColumnType="String")]
        public virtual string CtaHaberes {
            get {
                return this._ctaHaberes;
            }
            set {
                this._ctaHaberes = value;
            }
        }
        
        [Property("Cta_GALICIA", ColumnType="String")]
        public virtual string CtaGalicia {
            get {
                return this._ctaGalicia;
            }
            set {
                this._ctaGalicia = value;
            }
        }
        
        [Property("Cta_RIO", ColumnType="String")]
        public virtual string CtaRio {
            get {
                return this._ctaRio;
            }
            set {
                this._ctaRio = value;
            }
        }
        
        [Property("Cta_PARIBAS", ColumnType="String")]
        public virtual string CtaParibas {
            get {
                return this._ctaParibas;
            }
            set {
                this._ctaParibas = value;
            }
        }
        
        [Property("Tipo_de_Contrato", ColumnType="String")]
        public virtual string TipoDeContrato {
            get {
                return this._tipoDeContrato;
            }
            set {
                this._tipoDeContrato = value;
            }
        }
        
        [Property("num_Contrato", ColumnType="String")]
        public virtual string NumContrato {
            get {
                return this._numContrato;
            }
            set {
                this._numContrato = value;
            }
        }
        
        [Property("Fecha_de_Ingreso", ColumnType="DateTime", Update=false)]
        public virtual System.DateTime FechaDeIngreso {
            get {
                return this._fechaDeIngreso;
            }
            set {
                this._fechaDeIngreso = value;
            }
        }
        
        [Property("Fecha_Fin_Contrato", ColumnType="DateTime", Update=false)]
        public virtual System.DateTime FechaFinContrato {
            get {
                return this._fechaFinContrato;
            }
            set {
                this._fechaFinContrato = value;
            }
        }
        
        [Property("Activo", ColumnType="String", NotNull=true)]
        public virtual string Activo {
            get {
                return this._activo;
            }
            set {
                this._activo = value;
            }
        }
        
        [Property("Puesto", ColumnType="String")]
        public virtual string Puesto {
            get {
                return this._puesto;
            }
            set {
                this._puesto = value;
            }
        }
        
        [Property("Ultimo_Examen_Periodico", ColumnType="Timestamp", Update=false)]
        public virtual System.DateTime UltimoExamenPeriodico {
            get {
                return this._ultimoExamenPeriodico;
            }
            set {
                this._ultimoExamenPeriodico = value;
            }
        }
        
        [Property("foto", ColumnType="String")]
        public virtual string Foto {
            get {
                return this._foto;
            }
            set {
                this._foto = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Correctivo", Schema="dbo")]
    public partial class SolicitudCorrectivo : ActiveRecordBase<SolicitudCorrectivo> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private string _fallaReportada;
        
        private int _idPlazoAtencion;
        
        private System.DateTime _fechanotificacionCliente;
        
        private string _causaPosible;
        
        private string _personaReportoFalla;
        
        private string _presupuesto;
        
        private bool _penaliza;
        
        private int _idSitio;
        
        private System.DateTime _fechaResolucion;
        
        private string _contactoConformidadCliente;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("IdSolicitud", ColumnType="Int32", NotNull=true)]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("FallaReportada", ColumnType="String")]
        public virtual string FallaReportada {
            get {
                return this._fallaReportada;
            }
            set {
                this._fallaReportada = value;
            }
        }
        
        [Property("IdPlazoAtencion", ColumnType="Int32", NotNull=true)]
        public virtual int IdPlazoAtencion {
            get {
                return this._idPlazoAtencion;
            }
            set {
                this._idPlazoAtencion = value;
            }
        }
        
        [Property("FechaNotificacion_Cliente", ColumnType="DateTime")]
        public virtual System.DateTime FechanotificacionCliente {
            get {
                return this._fechanotificacionCliente;
            }
            set {
                this._fechanotificacionCliente = value;
            }
        }
        
        [Property("Causa_Posible", ColumnType="String")]
        public virtual string CausaPosible {
            get {
                return this._causaPosible;
            }
            set {
                this._causaPosible = value;
            }
        }
        
        [Property("PersonaReportoFalla", ColumnType="String")]
        public virtual string PersonaReportoFalla {
            get {
                return this._personaReportoFalla;
            }
            set {
                this._personaReportoFalla = value;
            }
        }
        
        [Property("Presupuesto", ColumnType="String")]
        public virtual string Presupuesto {
            get {
                return this._presupuesto;
            }
            set {
                this._presupuesto = value;
            }
        }
        
        [Property("Penaliza", ColumnType="Boolean")]
        public virtual bool Penaliza {
            get {
                return this._penaliza;
            }
            set {
                this._penaliza = value;
            }
        }
        
        [Property("IdSitio", ColumnType="Int32")]
        public virtual int IdSitio {
            get {
                return this._idSitio;
            }
            set {
                this._idSitio = value;
            }
        }
        
        [Property("FechaResolucion", ColumnType="DateTime")]
        public virtual System.DateTime FechaResolucion {
            get {
                return this._fechaResolucion;
            }
            set {
                this._fechaResolucion = value;
            }
        }
        
        [Property("Contacto_Conformidad_Cliente", ColumnType="String")]
        public virtual string ContactoConformidadCliente {
            get {
                return this._contactoConformidadCliente;
            }
            set {
                this._contactoConformidadCliente = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Obra", Schema="dbo")]
    public partial class SolicitudObra : ActiveRecordBase<SolicitudObra> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private string _descripcionTareas;
        
        private System.DateTime _fechaInicio;
        
        private System.DateTime _fechaFin;
        
        private string _requisitosAprovacion;
        
        private string _requisitosIngreso;
        
        private string _presupuesto;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Id_Solicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("Descripcion_tareas", ColumnType="String")]
        public virtual string DescripcionTareas {
            get {
                return this._descripcionTareas;
            }
            set {
                this._descripcionTareas = value;
            }
        }
        
        [Property("FechaInicio", ColumnType="DateTime")]
        public virtual System.DateTime FechaInicio {
            get {
                return this._fechaInicio;
            }
            set {
                this._fechaInicio = value;
            }
        }
        
        [Property("FechaFin", ColumnType="DateTime")]
        public virtual System.DateTime FechaFin {
            get {
                return this._fechaFin;
            }
            set {
                this._fechaFin = value;
            }
        }
        
        [Property("Requisitos_Aprovacion", ColumnType="String")]
        public virtual string RequisitosAprovacion {
            get {
                return this._requisitosAprovacion;
            }
            set {
                this._requisitosAprovacion = value;
            }
        }
        
        [Property("Requisitos_Ingreso", ColumnType="String")]
        public virtual string RequisitosIngreso {
            get {
                return this._requisitosIngreso;
            }
            set {
                this._requisitosIngreso = value;
            }
        }
        
        [Property("Presupuesto", ColumnType="String")]
        public virtual string Presupuesto {
            get {
                return this._presupuesto;
            }
            set {
                this._presupuesto = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Obra_Reporte_Tareas", Schema="dbo")]
    public partial class SolicitudObraReporteTareas : ActiveRecordBase<SolicitudObraReporteTareas> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private string _tarea;
        
        private string _descripcionTareas;
        
        private System.DateTime _fechaInicio;
        
        private System.DateTime _fechaFin;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Id_Solicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("Tarea", ColumnType="String")]
        public virtual string Tarea {
            get {
                return this._tarea;
            }
            set {
                this._tarea = value;
            }
        }
        
        [Property("Descripcion_tareas", ColumnType="String")]
        public virtual string DescripcionTareas {
            get {
                return this._descripcionTareas;
            }
            set {
                this._descripcionTareas = value;
            }
        }
        
        [Property("FechaInicio", ColumnType="DateTime")]
        public virtual System.DateTime FechaInicio {
            get {
                return this._fechaInicio;
            }
            set {
                this._fechaInicio = value;
            }
        }
        
        [Property("FechaFin", ColumnType="Timestamp")]
        public virtual System.DateTime FechaFin {
            get {
                return this._fechaFin;
            }
            set {
                this._fechaFin = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Reporte_Obra", Schema="dbo")]
    public partial class SolicitudReporteObra : ActiveRecordBase<SolicitudReporteObra> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private string _recibioConformeCliente;
        
        private string _seCumplieronRequisitosApr;
        
        private System.DateTime _fechaEntregaCliente;
        
        private System.DateTime _fechaActualizacion;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Id_Solicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("Recibio_Conforme_Cliente", ColumnType="String", NotNull=true)]
        public virtual string RecibioConformeCliente {
            get {
                return this._recibioConformeCliente;
            }
            set {
                this._recibioConformeCliente = value;
            }
        }
        
        [Property("Se_Cumplieron_Requisitos_Apr", ColumnType="String")]
        public virtual string SeCumplieronRequisitosApr {
            get {
                return this._seCumplieronRequisitosApr;
            }
            set {
                this._seCumplieronRequisitosApr = value;
            }
        }
        
        [Property("Fecha_Entrega_Cliente", ColumnType="DateTime")]
        public virtual System.DateTime FechaEntregaCliente {
            get {
                return this._fechaEntregaCliente;
            }
            set {
                this._fechaEntregaCliente = value;
            }
        }
        
        [Property("Fecha_Actualizacion", ColumnType="Timestamp")]
        public virtual System.DateTime FechaActualizacion {
            get {
                return this._fechaActualizacion;
            }
            set {
                this._fechaActualizacion = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud", Schema="dbo")]
    public partial class Solicitud : ActiveRecordBase<Solicitud> {
        
        private int _id_Solicitud;
        
        private int _idTipoSolicitud;
        
        private System.DateTime _fechaCreacion;
        
        private int _idUsuarioCreador;
        
        private string _status;
        
        private string _descripcion;
        
        private int _idCliente;
        
        private string _contacto;
        
        private string _contactoMail;
        
        private string _contactoTel;
        
        private string _nroOrdenCte;
        
        private string _aprobadorReprosusp;
        
        private System.DateTime _fechaSuspencion;
        
        private System.DateTime _fechaReprogramacion;
        
        private System.DateTime _proximaFechaInicio;
        
        private System.DateTime _proximaFechaFin;
        
        private int _idResponsable;
        
        private string _causa;
        
        private string _reporte;
        
        private int _idSolicitudInicial;
        
        private bool _aprobacionTecnica;
        
        private System.DateTime _fechaAprobacionTecnica;
        
        private bool _aprobacionCalidad;
        
        private System.DateTime _fechaAprobacionCalidad;
        
        private string _descripcionReporte;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id_Solicitud", ColumnType="Int32")]
        public virtual int Id_Solicitud {
            get {
                return this._id_Solicitud;
            }
            set {
                this._id_Solicitud = value;
            }
        }
        
        [Property("IdTipoSolicitud", ColumnType="Int32")]
        public virtual int IdTipoSolicitud {
            get {
                return this._idTipoSolicitud;
            }
            set {
                this._idTipoSolicitud = value;
            }
        }
        
        [Property("FechaCreacion", ColumnType="DateTime")]
        public virtual System.DateTime FechaCreacion {
            get {
                return this._fechaCreacion;
            }
            set {
                this._fechaCreacion = value;
            }
        }
        
        [Property("IdUsuarioCreador", ColumnType="Int32")]
        public virtual int IdUsuarioCreador {
            get {
                return this._idUsuarioCreador;
            }
            set {
                this._idUsuarioCreador = value;
            }
        }
        
        [Property("Status", ColumnType="String")]
        public virtual string Status {
            get {
                return this._status;
            }
            set {
                this._status = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
        
        [Property("IdCliente", ColumnType="Int32")]
        public virtual int IdCliente {
            get {
                return this._idCliente;
            }
            set {
                this._idCliente = value;
            }
        }
        
        [Property("Contacto", ColumnType="String")]
        public virtual string Contacto {
            get {
                return this._contacto;
            }
            set {
                this._contacto = value;
            }
        }
        
        [Property("Contacto_Mail", ColumnType="String")]
        public virtual string ContactoMail {
            get {
                return this._contactoMail;
            }
            set {
                this._contactoMail = value;
            }
        }
        
        [Property("Contacto_Tel", ColumnType="String")]
        public virtual string ContactoTel {
            get {
                return this._contactoTel;
            }
            set {
                this._contactoTel = value;
            }
        }
        
        [Property("NroOrdenCte", ColumnType="String")]
        public virtual string NroOrdenCte {
            get {
                return this._nroOrdenCte;
            }
            set {
                this._nroOrdenCte = value;
            }
        }
        
        [Property("Aprobador_ReproSusp", ColumnType="String")]
        public virtual string AprobadorReprosusp {
            get {
                return this._aprobadorReprosusp;
            }
            set {
                this._aprobadorReprosusp = value;
            }
        }
        
        [Property("Fecha_Suspencion", ColumnType="DateTime")]
        public virtual System.DateTime FechaSuspencion {
            get {
                return this._fechaSuspencion;
            }
            set {
                this._fechaSuspencion = value;
            }
        }
        
        [Property("Fecha_Reprogramacion", ColumnType="DateTime")]
        public virtual System.DateTime FechaReprogramacion {
            get {
                return this._fechaReprogramacion;
            }
            set {
                this._fechaReprogramacion = value;
            }
        }
        
        [Property("Proxima_Fecha_inicio", ColumnType="DateTime")]
        public virtual System.DateTime ProximaFechaInicio {
            get {
                return this._proximaFechaInicio;
            }
            set {
                this._proximaFechaInicio = value;
            }
        }
        
        [Property("Proxima_Fecha_Fin", ColumnType="DateTime")]
        public virtual System.DateTime ProximaFechaFin {
            get {
                return this._proximaFechaFin;
            }
            set {
                this._proximaFechaFin = value;
            }
        }
        
        [Property("IdResponsable", ColumnType="Int32")]
        public virtual int IdResponsable {
            get {
                return this._idResponsable;
            }
            set {
                this._idResponsable = value;
            }
        }
        
        [Property("Causa", ColumnType="String")]
        public virtual string Causa {
            get {
                return this._causa;
            }
            set {
                this._causa = value;
            }
        }
        
        [Property("Reporte", ColumnType="String")]
        public virtual string Reporte {
            get {
                return this._reporte;
            }
            set {
                this._reporte = value;
            }
        }
        
        [Property("id_Solicitud_Inicial", ColumnType="Int32")]
        public virtual int IdSolicitudInicial {
            get {
                return this._idSolicitudInicial;
            }
            set {
                this._idSolicitudInicial = value;
            }
        }
        
        [Property("Aprobacion_Tecnica", ColumnType="Boolean")]
        public virtual bool AprobacionTecnica {
            get {
                return this._aprobacionTecnica;
            }
            set {
                this._aprobacionTecnica = value;
            }
        }
        
        [Property("Fecha_Aprobacion_Tecnica", ColumnType="DateTime")]
        public virtual System.DateTime FechaAprobacionTecnica {
            get {
                return this._fechaAprobacionTecnica;
            }
            set {
                this._fechaAprobacionTecnica = value;
            }
        }
        
        [Property("Aprobacion_Calidad", ColumnType="Boolean")]
        public virtual bool AprobacionCalidad {
            get {
                return this._aprobacionCalidad;
            }
            set {
                this._aprobacionCalidad = value;
            }
        }
        
        [Property("Fecha_Aprobacion_Calidad", ColumnType="DateTime")]
        public virtual System.DateTime FechaAprobacionCalidad {
            get {
                return this._fechaAprobacionCalidad;
            }
            set {
                this._fechaAprobacionCalidad = value;
            }
        }
        
        [Property("Descripcion_Reporte", ColumnType="String")]
        public virtual string DescripcionReporte {
            get {
                return this._descripcionReporte;
            }
            set {
                this._descripcionReporte = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Recursos_Vehiculos", Schema="dbo")]
    public partial class SolicitudRecursosVehiculos : ActiveRecordBase<SolicitudRecursosVehiculos> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private int _idVehiculo;
        
        private decimal _km;
        
        private decimal _horas;
        
        private System.DateTime _fecha;
        
        private string _detalle;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Id_Solicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("Id_Vehiculo", ColumnType="Int32")]
        public virtual int IdVehiculo {
            get {
                return this._idVehiculo;
            }
            set {
                this._idVehiculo = value;
            }
        }
        
        [Property("Km", ColumnType="Decimal")]
        public virtual decimal Km {
            get {
                return this._km;
            }
            set {
                this._km = value;
            }
        }
        
        [Property("Horas", ColumnType="Decimal")]
        public virtual decimal Horas {
            get {
                return this._horas;
            }
            set {
                this._horas = value;
            }
        }
        
        [Property("Fecha", ColumnType="DateTime")]
        public virtual System.DateTime Fecha {
            get {
                return this._fecha;
            }
            set {
                this._fecha = value;
            }
        }
        
        [Property("Detalle", ColumnType="String")]
        public virtual string Detalle {
            get {
                return this._detalle;
            }
            set {
                this._detalle = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Capacitacion", Schema="dbo")]
    public partial class SolicitudCapacitacion : ActiveRecordBase<SolicitudCapacitacion> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private System.DateTime _fechaInicio;
        
        private System.DateTime _fechaFin;
        
        private string _descripcion;
        
        private string _nivel;
        
        private decimal _duracion;
        
        private string _areaEstudio;
        
        private string _instructor;
        
        private string _entidadEducativa;
        
        private string _puntuacionExamen;
        
        private int _idEmpleado;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("IdSolicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("FechaInicio", ColumnType="DateTime")]
        public virtual System.DateTime FechaInicio {
            get {
                return this._fechaInicio;
            }
            set {
                this._fechaInicio = value;
            }
        }
        
        [Property("FechaFin", ColumnType="Timestamp")]
        public virtual System.DateTime FechaFin {
            get {
                return this._fechaFin;
            }
            set {
                this._fechaFin = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
        
        [Property("Nivel", ColumnType="String")]
        public virtual string Nivel {
            get {
                return this._nivel;
            }
            set {
                this._nivel = value;
            }
        }
        
        [Property("Duracion", ColumnType="Decimal")]
        public virtual decimal Duracion {
            get {
                return this._duracion;
            }
            set {
                this._duracion = value;
            }
        }
        
        [Property("Area_Estudio", ColumnType="String")]
        public virtual string AreaEstudio {
            get {
                return this._areaEstudio;
            }
            set {
                this._areaEstudio = value;
            }
        }
        
        [Property("Instructor", ColumnType="String")]
        public virtual string Instructor {
            get {
                return this._instructor;
            }
            set {
                this._instructor = value;
            }
        }
        
        [Property("Entidad_Educativa", ColumnType="String")]
        public virtual string EntidadEducativa {
            get {
                return this._entidadEducativa;
            }
            set {
                this._entidadEducativa = value;
            }
        }
        
        [Property("Puntuacion_Examen", ColumnType="String")]
        public virtual string PuntuacionExamen {
            get {
                return this._puntuacionExamen;
            }
            set {
                this._puntuacionExamen = value;
            }
        }
        
        [Property("Id_Empleado", ColumnType="Int32", NotNull=true)]
        public virtual int IdEmpleado {
            get {
                return this._idEmpleado;
            }
            set {
                this._idEmpleado = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Licencias", Schema="dbo")]
    public partial class SolicitudLicencias : ActiveRecordBase<SolicitudLicencias> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private System.DateTime _fechaInicio;
        
        private System.DateTime _fechaFin;
        
        private string _descripcion;
        
        private decimal _duracion;
        
        private int _idTipolicencia;
        
        private int _idEmpleado;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("IdSolicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("FechaInicio", ColumnType="DateTime")]
        public virtual System.DateTime FechaInicio {
            get {
                return this._fechaInicio;
            }
            set {
                this._fechaInicio = value;
            }
        }
        
        [Property("FechaFin", ColumnType="DateTime")]
        public virtual System.DateTime FechaFin {
            get {
                return this._fechaFin;
            }
            set {
                this._fechaFin = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
        
        [Property("Duracion", ColumnType="Decimal")]
        public virtual decimal Duracion {
            get {
                return this._duracion;
            }
            set {
                this._duracion = value;
            }
        }
        
        [Property("Id_TipoLicencia", ColumnType="Int32")]
        public virtual int IdTipolicencia {
            get {
                return this._idTipolicencia;
            }
            set {
                this._idTipolicencia = value;
            }
        }
        
        [Property("Id_Empleado", ColumnType="Int32", NotNull=true)]
        public virtual int IdEmpleado {
            get {
                return this._idEmpleado;
            }
            set {
                this._idEmpleado = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Francos_Compensatorios", Schema="dbo")]
    public partial class SolicitudFrancosCompensatorios : ActiveRecordBase<SolicitudFrancosCompensatorios> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private System.DateTime _fechaInicio;
        
        private System.DateTime _fechaFin;
        
        private decimal _duracion;
        
        private string _descripcion;
        
        private string _conElConsentimiento;
        
        private int _idEmpleado;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("IdSolicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("FechaInicio", ColumnType="DateTime")]
        public virtual System.DateTime FechaInicio {
            get {
                return this._fechaInicio;
            }
            set {
                this._fechaInicio = value;
            }
        }
        
        [Property("FechaFin", ColumnType="DateTime")]
        public virtual System.DateTime FechaFin {
            get {
                return this._fechaFin;
            }
            set {
                this._fechaFin = value;
            }
        }
        
        [Property("Duracion", ColumnType="Decimal")]
        public virtual decimal Duracion {
            get {
                return this._duracion;
            }
            set {
                this._duracion = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
        
        [Property("ConElConsentimiento", ColumnType="String")]
        public virtual string ConElConsentimiento {
            get {
                return this._conElConsentimiento;
            }
            set {
                this._conElConsentimiento = value;
            }
        }
        
        [Property("Id_Empleado", ColumnType="Int32", NotNull=true)]
        public virtual int IdEmpleado {
            get {
                return this._idEmpleado;
            }
            set {
                this._idEmpleado = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Tareas_Generales", Schema="dbo")]
    public partial class SolicitudTareasGenerales : ActiveRecordBase<SolicitudTareasGenerales> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private System.DateTime _fechaInicio;
        
        private System.DateTime _fechaFin;
        
        private string _descripcion;
        
        private decimal _duracion;
        
        private int _idTipotarea;
        
        private int _idEmpleado;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("IdSolicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("FechaInicio", ColumnType="DateTime")]
        public virtual System.DateTime FechaInicio {
            get {
                return this._fechaInicio;
            }
            set {
                this._fechaInicio = value;
            }
        }
        
        [Property("FechaFin", ColumnType="DateTime")]
        public virtual System.DateTime FechaFin {
            get {
                return this._fechaFin;
            }
            set {
                this._fechaFin = value;
            }
        }
        
        [Property("Descripcion", ColumnType="String")]
        public virtual string Descripcion {
            get {
                return this._descripcion;
            }
            set {
                this._descripcion = value;
            }
        }
        
        [Property("Duracion", ColumnType="Decimal")]
        public virtual decimal Duracion {
            get {
                return this._duracion;
            }
            set {
                this._duracion = value;
            }
        }
        
        [Property("Id_TipoTarea", ColumnType="Int32")]
        public virtual int IdTipotarea {
            get {
                return this._idTipotarea;
            }
            set {
                this._idTipotarea = value;
            }
        }
        
        [Property("Id_Empleado", ColumnType="Int32", NotNull=true)]
        public virtual int IdEmpleado {
            get {
                return this._idEmpleado;
            }
            set {
                this._idEmpleado = value;
            }
        }
    }
    
    [ActiveRecord("Solicitud_Gastos", Schema="dbo")]
    public partial class SolicitudGastos : ActiveRecordBase<SolicitudGastos> {
        
        private int _id;
        
        private int _idSolicitud;
        
        private System.DateTime _fecha;
        
        private string _detalle;
        
        private decimal _total;
        
        [PrimaryKey(PrimaryKeyType.Native, "Id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("IdSolicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("Fecha", ColumnType="DateTime")]
        public virtual System.DateTime Fecha {
            get {
                return this._fecha;
            }
            set {
                this._fecha = value;
            }
        }
        
        [Property("Detalle", ColumnType="String")]
        public virtual string Detalle {
            get {
                return this._detalle;
            }
            set {
                this._detalle = value;
            }
        }
        
        [Property("Total", ColumnType="Decimal")]
        public virtual decimal Total {
            get {
                return this._total;
            }
            set {
                this._total = value;
            }
        }
    }
}
