//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gos.Events {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("Events", Schema="dbo")]
    public partial class Events : ActiveRecordBase<Events> {
        
        private int _idEvent;
        
        private string _modulo;
        
        private string _detalle;
        
        private string _usuario;
        
        private System.DateTime _fecha;
        
        [PrimaryKey(PrimaryKeyType.Native, "IdEvent", ColumnType="Int32")]
        public virtual int IdEvent {
            get {
                return this._idEvent;
            }
            set {
                this._idEvent = value;
            }
        }
        
        [Property("Modulo", ColumnType="String", NotNull=true)]
        public virtual string Modulo {
            get {
                return this._modulo;
            }
            set {
                this._modulo = value;
            }
        }
        
        [Property("Detalle", ColumnType="String", NotNull=true)]
        public virtual string Detalle {
            get {
                return this._detalle;
            }
            set {
                this._detalle = value;
            }
        }
        
        [Property("usuario", ColumnType="String", NotNull=true)]
        public virtual string Usuario {
            get {
                return this._usuario;
            }
            set {
                this._usuario = value;
            }
        }
        
        [Property("Fecha", ColumnType="DateTime", NotNull=true)]
        public virtual System.DateTime Fecha {
            get {
                return this._fecha;
            }
            set {
                this._fecha = value;
            }
        }
    }
}
