//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antares.model {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("SolicitudAdjuntos", Schema="dbo")]
    public partial class SolicitudAdjuntos : ActiveRecordBase<SolicitudAdjuntos> {
        
        private short _idSolAdjunto;
        
        private int _idSolicitud;
        
        private int _idAdjunto;
        
        [PrimaryKey(PrimaryKeyType.Native, "IdSolAdjunto", ColumnType="Int16")]
        public virtual short IdSolAdjunto {
            get {
                return this._idSolAdjunto;
            }
            set {
                this._idSolAdjunto = value;
            }
        }
        
        [Property("IdSolicitud", ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property("IdAdjunto", ColumnType="Int32")]
        public virtual int IdAdjunto {
            get {
                return this._idAdjunto;
            }
            set {
                this._idAdjunto = value;
            }
        }
    }
    
    [ActiveRecord("Adjunto", Schema="dbo")]
    public partial class Adjunto : ActiveRecordBase<Adjunto> {
        
        private int _idAdjunto;
        
        private string _pathFile;
        
        private string _fileName;
        
        private string _contentType;
        
        private System.DateTime _date;
        
        private int _size;
        
        private bool _calidad;
        
        [PrimaryKey(PrimaryKeyType.Native, "IdAdjunto", ColumnType="Int32")]
        public virtual int IdAdjunto {
            get {
                return this._idAdjunto;
            }
            set {
                this._idAdjunto = value;
            }
        }
        
        [Property("PathFile", ColumnType="String")]
        public virtual string PathFile {
            get {
                return this._pathFile;
            }
            set {
                this._pathFile = value;
            }
        }
        
        [Property("FileName", ColumnType="String")]
        public virtual string FileName {
            get {
                return this._fileName;
            }
            set {
                this._fileName = value;
            }
        }
        
        [Property("ContentType", ColumnType="String")]
        public virtual string ContentType {
            get {
                return this._contentType;
            }
            set {
                this._contentType = value;
            }
        }
        
        [Property("Date", ColumnType="Timestamp")]
        public virtual System.DateTime Date {
            get {
                return this._date;
            }
            set {
                this._date = value;
            }
        }
        
        [Property("Size", ColumnType="Int32")]
        public virtual int Size {
            get {
                return this._size;
            }
            set {
                this._size = value;
            }
        }
        
        [Property("Calidad", ColumnType="Boolean")]
        public virtual bool Calidad {
            get {
                return this._calidad;
            }
            set {
                this._calidad = value;
            }
        }
    }
}
