//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antares.model {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("TipoEvento", Schema="dbo")]
    public partial class TipoEvento : ActiveRecordBase<TipoEvento> {
        
        private int _idTipoEvento;
        
        private string _nombre;
        
        [PrimaryKey(PrimaryKeyType.Native, "IdTipoEvento", ColumnType="Int32")]
        public virtual int IdTipoEvento {
            get {
                return this._idTipoEvento;
            }
            set {
                this._idTipoEvento = value;
            }
        }
        
        [Property("Nombre", ColumnType="String", NotNull=true)]
        public virtual string Nombre {
            get {
                return this._nombre;
            }
            set {
                this._nombre = value;
            }
        }
    }
    
    [ActiveRecord("Evento", Schema="dbo")]
    public partial class Evento : ActiveRecordBase<Evento> {
        
        private long _idEvento;
        
        private int _idTipoEvento;
        
        private int _idUsuario;
        
        private System.DateTime _fecha;
        
        private string _host;
        
        private string _detalle;
        
        [PrimaryKey(PrimaryKeyType.Native, "IdEvento", ColumnType="Int64")]
        public virtual long IdEvento {
            get {
                return this._idEvento;
            }
            set {
                this._idEvento = value;
            }
        }
        
        [Property("IdTipoEvento", ColumnType="Int32", NotNull=true)]
        public virtual int IdTipoEvento {
            get {
                return this._idTipoEvento;
            }
            set {
                this._idTipoEvento = value;
            }
        }
        
        [Property("IdUsuario", ColumnType="Int32", NotNull=true)]
        public virtual int IdUsuario {
            get {
                return this._idUsuario;
            }
            set {
                this._idUsuario = value;
            }
        }
        
        [Property("Fecha", ColumnType="Timestamp", NotNull=true)]
        public virtual System.DateTime Fecha {
            get {
                return this._fecha;
            }
            set {
                this._fecha = value;
            }
        }
        
        [Property("Host", ColumnType="String", NotNull=true)]
        public virtual string Host {
            get {
                return this._host;
            }
            set {
                this._host = value;
            }
        }
        
        [Property("Detalle", ColumnType="StringClob")]
        public virtual string Detalle {
            get {
                return this._detalle;
            }
            set {
                this._detalle = value;
            }
        }
    }
}
