//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antares.model {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("Tareas_Realizadas", Schema="dbo")]
    public partial class TareasRealizadas : ActiveRecordBase<TareasRealizadas> {
        
        private int _id;
        
        private int _idDestino;
        
        private int _idTarea;
        
        private int _idEmpleados;
        
        private string _fecha;
        
        private string _duracion;
        
        private string _semana;
        
        private string _tipoTarea;
        
        private string _comentarios;
        
        private string _idxInforme;
        
        private int _batchId;
        
        [PrimaryKey(PrimaryKeyType.Native, "id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("id_destino", ColumnType="Int32", NotNull=true)]
        public virtual int IdDestino {
            get {
                return this._idDestino;
            }
            set {
                this._idDestino = value;
            }
        }
        
        [Property("id_tarea", ColumnType="Int32", NotNull=true)]
        public virtual int IdTarea {
            get {
                return this._idTarea;
            }
            set {
                this._idTarea = value;
            }
        }
        
        [Property("id_Empleados", ColumnType="Int32", NotNull=true)]
        public virtual int IdEmpleados {
            get {
                return this._idEmpleados;
            }
            set {
                this._idEmpleados = value;
            }
        }
        
        [Property("fecha", ColumnType="AnsiChar", NotNull=true)]
        public virtual string Fecha {
            get {
                return this._fecha;
            }
            set {
                this._fecha = value;
            }
        }
        
        [Property("duracion", ColumnType="AnsiChar")]
        public virtual string Duracion {
            get {
                return this._duracion;
            }
            set {
                this._duracion = value;
            }
        }
        
        [Property("semana", ColumnType="AnsiChar")]
        public virtual string Semana {
            get {
                return this._semana;
            }
            set {
                this._semana = value;
            }
        }
        
        [Property("Tipo_Tarea", ColumnType="AnsiChar")]
        public virtual string TipoTarea {
            get {
                return this._tipoTarea;
            }
            set {
                this._tipoTarea = value;
            }
        }
        
        [Property("Comentarios", ColumnType="AnsiChar")]
        public virtual string Comentarios {
            get {
                return this._comentarios;
            }
            set {
                this._comentarios = value;
            }
        }
        
        [Property("idx_Informe", ColumnType="AnsiChar", NotNull=true)]
        public virtual string IdxInforme {
            get {
                return this._idxInforme;
            }
            set {
                this._idxInforme = value;
            }
        }
        
        [Property("batch_id", ColumnType="Int32", NotNull=true)]
        public virtual int BatchId {
            get {
                return this._batchId;
            }
            set {
                this._batchId = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class Solicitud_Relacion : ActiveRecordBase<Solicitud_Relacion> {
        
        private int _idSolRel;
        
        private int _idSolicitud;
        
        private int _idSolicitud_Relacionada;
        
        [PrimaryKey(PrimaryKeyType.Native, ColumnType="Int32")]
        public virtual int IdSolRel {
            get {
                return this._idSolRel;
            }
            set {
                this._idSolRel = value;
            }
        }
        
        [Property(ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property(ColumnType="Int32", NotNull=true, Unique=true)]
        public virtual int IdSolicitud_Relacionada {
            get {
                return this._idSolicitud_Relacionada;
            }
            set {
                this._idSolicitud_Relacionada = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class Estados : ActiveRecordBase<Estados> {
        
        private short _idEstado;
        
        private string _detalle;
        
        [PrimaryKey(PrimaryKeyType.Native, ColumnType="Int16")]
        public virtual short IdEstado {
            get {
                return this._idEstado;
            }
            set {
                this._idEstado = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string Detalle {
            get {
                return this._detalle;
            }
            set {
                this._detalle = value;
            }
        }
    }
    
    [ActiveRecord("Tareas_Horas", Schema="dbo")]
    public partial class TareasHoras : ActiveRecordBase<TareasHoras> {
        
        private int _id;
        
        private int _idTarea;
        
        private int _idEmpleados;
        
        private int _idTipotarea;
        
        private System.DateTime _fecha;
        
        private double _duracion;
        
        private int _semana;
        
        private string _comentarios;
        
        [PrimaryKey(PrimaryKeyType.Native, "id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("id_tarea", ColumnType="Int32")]
        public virtual int IdTarea {
            get {
                return this._idTarea;
            }
            set {
                this._idTarea = value;
            }
        }
        
        [Property("id_Empleados", ColumnType="Int32")]
        public virtual int IdEmpleados {
            get {
                return this._idEmpleados;
            }
            set {
                this._idEmpleados = value;
            }
        }
        
        [Property("id_TipoTarea", ColumnType="Int32")]
        public virtual int IdTipotarea {
            get {
                return this._idTipotarea;
            }
            set {
                this._idTipotarea = value;
            }
        }
        
        [Property("fecha", ColumnType="DateTime")]
        public virtual System.DateTime Fecha {
            get {
                return this._fecha;
            }
            set {
                this._fecha = value;
            }
        }
        
        [Property("duracion", ColumnType="Double")]
        public virtual double Duracion {
            get {
                return this._duracion;
            }
            set {
                this._duracion = value;
            }
        }
        
        [Property("semana", ColumnType="Int32")]
        public virtual int Semana {
            get {
                return this._semana;
            }
            set {
                this._semana = value;
            }
        }
        
        [Property("Comentarios", ColumnType="String")]
        public virtual string Comentarios {
            get {
                return this._comentarios;
            }
            set {
                this._comentarios = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class VehiculosKilometros : ActiveRecordBase<VehiculosKilometros> {
        
        private long _idVehiculosKilometros;
        
        private int _idSolicitud;
        
        private int _idVehiculoSolicitud;
        
        private double _kilometros;
        
        private double _tiempo;
        
        private System.DateTime _fecha;
        
        [PrimaryKey(PrimaryKeyType.Native, ColumnType="Int64")]
        public virtual long IdVehiculosKilometros {
            get {
                return this._idVehiculosKilometros;
            }
            set {
                this._idVehiculosKilometros = value;
            }
        }
        
        [Property(ColumnType="Int32")]
        public virtual int IdSolicitud {
            get {
                return this._idSolicitud;
            }
            set {
                this._idSolicitud = value;
            }
        }
        
        [Property(ColumnType="Int32")]
        public virtual int IdVehiculoSolicitud {
            get {
                return this._idVehiculoSolicitud;
            }
            set {
                this._idVehiculoSolicitud = value;
            }
        }
        
        [Property(ColumnType="Double")]
        public virtual double Kilometros {
            get {
                return this._kilometros;
            }
            set {
                this._kilometros = value;
            }
        }
        
        [Property(ColumnType="Double")]
        public virtual double Tiempo {
            get {
                return this._tiempo;
            }
            set {
                this._tiempo = value;
            }
        }
        
        [Property(ColumnType="DateTime")]
        public virtual System.DateTime Fecha {
            get {
                return this._fecha;
            }
            set {
                this._fecha = value;
            }
        }
    }
}
