//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antares.model {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("Acciones", Schema="dbo")]
    public partial class Acciones : ActiveRecordBase<Acciones> {
        
        private int _idAccion;
        
        private string _objeto;
        
        private string _valor;
        
        [PrimaryKey(PrimaryKeyType.Native, "IdAccion", ColumnType="Int32")]
        public virtual int IdAccion {
            get {
                return this._idAccion;
            }
            set {
                this._idAccion = value;
            }
        }
        
        [Property("Objeto", ColumnType="String")]
        public virtual string Objeto {
            get {
                return this._objeto;
            }
            set {
                this._objeto = value;
            }
        }
        
        [Property("Valor", ColumnType="String")]
        public virtual string Valor {
            get {
                return this._valor;
            }
            set {
                this._valor = value;
            }
        }
    }
    
    [ActiveRecord("AccionPerfil", Schema="dbo")]
    public partial class AccionPerfil : ActiveRecordBase<AccionPerfil> {
        
        private int _id;
        
        private int _idPerfil;
        
        private int _idAccion;
        
        private System.DateTime _fechaActualizacion;
        
        [PrimaryKey(PrimaryKeyType.Native, "id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("IdPerfil", ColumnType="Int32")]
        public virtual int IdPerfil {
            get {
                return this._idPerfil;
            }
            set {
                this._idPerfil = value;
            }
        }
        
        [Property("IdAccion", ColumnType="Int32")]
        public virtual int IdAccion {
            get {
                return this._idAccion;
            }
            set {
                this._idAccion = value;
            }
        }
        
        [Property("FechaActualizacion", ColumnType="Timestamp")]
        public virtual System.DateTime FechaActualizacion {
            get {
                return this._fechaActualizacion;
            }
            set {
                this._fechaActualizacion = value;
            }
        }
    }
    
    [ActiveRecord("Perfiles", Schema="dbo")]
    public partial class Perfiles : ActiveRecordBase<Perfiles> {
        
        private int _idPerfil;
        
        private string _detalle;
        
        [PrimaryKey(PrimaryKeyType.Native, "IdPerfil", ColumnType="Int32")]
        public virtual int IdPerfil {
            get {
                return this._idPerfil;
            }
            set {
                this._idPerfil = value;
            }
        }
        
        [Property("Detalle", ColumnType="String", NotNull=true)]
        public virtual string Detalle {
            get {
                return this._detalle;
            }
            set {
                this._detalle = value;
            }
        }
    }
    
    [ActiveRecord("Usuarios", Schema="dbo")]
    public partial class Usuarios : ActiveRecordBase<Usuarios> {
        
        private int _idUsuario;
        
        private string _nombre;
        
        private string _loginName;
        
        private string _password;
        
        private int _idPerfil;
        
        private int _perfiles;
        
        private string _foto;
        
        [PrimaryKey(PrimaryKeyType.Native, "IdUsuario", ColumnType="Int32")]
        public virtual int IdUsuario {
            get {
                return this._idUsuario;
            }
            set {
                this._idUsuario = value;
            }
        }
        
        [Property("Nombre", ColumnType="String")]
        public virtual string Nombre {
            get {
                return this._nombre;
            }
            set {
                this._nombre = value;
            }
        }
        
        [Property("loginName", ColumnType="String")]
        public virtual string LoginName {
            get {
                return this._loginName;
            }
            set {
                this._loginName = value;
            }
        }
        
        [Property("Password", ColumnType="String")]
        public virtual string Password {
            get {
                return this._password;
            }
            set {
                this._password = value;
            }
        }
        
        [Property("IdPerfil", ColumnType="Int32")]
        public virtual int IdPerfil {
            get {
                return this._idPerfil;
            }
            set {
                this._idPerfil = value;
            }
        }
        
        [Property("Perfiles", ColumnType="Int32")]
        public virtual int Perfiles {
            get {
                return this._perfiles;
            }
            set {
                this._perfiles = value;
            }
        }
        
        [Property("Foto", ColumnType="String")]
        public virtual string Foto {
            get {
                return this._foto;
            }
            set {
                this._foto = value;
            }
        }
    }
}
